### ISSUE TITLE
Zenodo Badge on Publication Entry

### ISSUE THREAD

**Issue by bbarad** [fraser-lab/fraser-lab.github.io#21]
Support zenodo release badges on publication entries, now that we are doing releases for most of our papers.

**Comment by bbarad** [comment]
Example zenodo badge: [![DOI](https://zenodo.org/badge/47163753.svg)](https://zenodo.org/badge/latestdoi/47163753)

Just make an image with `src=uid.svg` and wrap the link with `href=https://`... around it.

**Comment by idyoung** [comment]
Badges are added now. Open to suggestions for if they need more text describing what they're linking to.

**Comment by bbarad** [comment]
Love it! Might change out "zenodo record" for "source code" but I love having an optional description!

**Comment by idyoung** [comment]
I only hesitate because the other case already on the website seems to be more than source code (and there are folks who will use github+zenodo to just dump files). Do we want to treat that as off-label use?

**Comment by bbarad** [comment]
Aha! No, sharing data on zenodo is def on-label. Github + zenodo is kind of a diff workflow from pure zenodo, so I am not sure what the perfect solution is - maybe people can use the description section of the record to solve that like you did!

**Comment by bbarad** [comment]
Very excited to copy this feature for benjaminbarad.com.
