### ISSUE TITLE
Member bio text does not line up with top of member photo

### ISSUE THREAD

**Issue by rediaz111** [fraser-lab/fraser-lab.github.io#48]
<img width="815" alt="Screen Shot 2022-09-21 at 14 44 46" src="https://user-images.githubusercontent.com/32281616/191616117-c7bd9d30-b749-4952-9f5f-6b47f655805f.png">
The member bio text does not start at the same height as the member photo.

**Comment by dhogan-io** [comment]
Fixed: https://github.com/fraser-lab/fraser-lab.github.io/commit/55b085548e5249d94ede5359262c9d99ae3efd16
