### ISSUE TITLE
Publications page is getting too long.

### ISSUE THREAD

**Issue by bbarad** [fraser-lab/fraser-lab.github.io#6]
We are beginning to need to paginate the publications page. This should be possible to do using Jekyll Collections but will require investigation.

**Comment by fraserlab** [comment]
not super into that idea - would rather longer load times...

On Mon, Dec 7, 2015 at 3:53 PM Benjamin Barad <notifications@github.com>
wrote:

> We are beginning to need to paginate the publications page. This should be
> possible to do using Jekyll Collections but will require investigation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fraser-lab/fraser-lab.github.io/issues/6>.
>
-- 
--
James Fraser, PhD
Assistant Professor
Department of Bioengineering and Therapeutic Sciences
Office: S472E Genentech Hall, Lab: S476 Genentech Hall
jaimefraser@gmail.com // jfraser@fraserlab.com
please do NOT use james.fraser@ucsf.edu
(415) 493-8421
http://www.fraserlab.com

**Comment by bbarad** [comment]
Would a live-paginating on scroll make it better? or do you just want to be able to cmd-f whatever you want?
